# Generated by Django 4.0.3 on 2022-03-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
