# Generated by Django 4.0.3 on 2022-03-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_java'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='question_database',
        ),
    ]
