# Generated by Django 4.0.3 on 2022-06-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_test_number_remove_user_detail_no_of_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='test_num',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.test_number'),
        ),
        migrations.AlterField(
            model_name='test_number',
            name='algorithm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_number',
            name='database',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_number',
            name='java',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_number',
            name='python',
            field=models.IntegerField(default=0),
        ),
    ]
