# Generated by Django 4.0.3 on 2022-06-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_user_detail_test_num_alter_test_number_algorithm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='test_num',
        ),
        migrations.AddField(
            model_name='test_number',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.user_detail'),
        ),
    ]
