# Generated by Django 4.0.3 on 2022-06-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_test_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_details',
            new_name='test_detail',
        ),
    ]
